### ISSUE TITLE
NPE occurs while loading the game with GooKeeper template

### ISSUE THREAD

**Issue by ujjman** [Terasology/GooKeeper#54]
while loading the game with `GooKeeper` template, as soon as awaiting character spawn displays, a NPE uccurs,

**Steps to reproduce**
1. Open the game and select `singleplayer`
2. Load the game with `GooKeeper` template
3. As soon as `Awaiting character spawn` displays, error occurs
![e4](https://user-images.githubusercontent.com/49057926/143385614-a80a3732-cc32-4050-8a5f-910dde233b52.png)

**Comment by skaldarnar** [comment]
Module has been archived and is out of maintenance from the Terasology team.
